node{
    stage('Git Checkout'){
        git branch: 'main', url: 'https://github.com/kelvinduan2020/20210908-NodeJsProject.git'
    }
    
    stage('Deploy on Kubernetes'){
        sshagent(['k8s-master']) {
            sh 'scp -o StrictHostKeyChecking=no kubernetes/nodejsapp.yaml vagrant@192.168.0.106:/home/vagrant'
            script {
                try {
                    sh 'ssh vagrant@192.168.0.106 kubectl apply -f .'
                } catch(error) {
                    sh 'ssh vagrant@192.168.0.106 kubectl create -f .'
                }
            }
        }
    }
}
